
###
#
#   dictCC2CN #Two Letter ISO Country Code to Country Name
#   dictCC3CN #Three Letter ISO Country Code to Country Name
#
###

#// SOURCEed from http://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml
dictNetProto_byNumber = {
    0:{"keyword":None,"protocol":None,"refLink":[]},
    1:{"keyword":"ICMP","protocol":"Internet Control Message","refLink":["http://www.iana.org/go/rfc792"]},
    2:{"keyword":None,"protocol":None,"refLink":[]},
    6:{"keyword":"TCP","protocol":"Transmission Control","refLink":["http://www.iana.org/go/rfc793"]},
    17:{"keyword":"UDP","protocol":"User Datagram","refLink":["http://www.iana.org/go/rfc768","http://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml#Jon_Postel"]},

}

#// http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml
dictNetPort_byNumber = {
    0:{"serviceName":None,"tranProto":[{"protoKeyWord":None,"dscrpt":None,"refLinks":[]}]}, 
    22:{"serviceName":'ssh',"tranProto":[
        {"protoKeyWord":"TCP","dscrpt":"The Secure Shell (SSH) Protocol","refLinks":[]},
        {"protoKeyWord":"UDP","dscrpt":"The Secure Shell (SSH) Protocol","refLinks":[]},
        {"protoKeyWord":"sctp","dscrpt":"The Secure Shell (SSH) Protocol","refLinks":["http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml#Jon_Postel","http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml#Randall_Stewart"]}
        ]},
    

}

dictCC3CN = {}

dictCC2CN = {
        'AF':'Afghanistan',
        'AD':'Andorra',
        'AE':'United Arab Emirates',
        'AG':'Antigua and Barbuda',
        'AI':'Anguilla',
        'AL':'Albania',
        'AM':'Armenia',
        'AN':'Netherlands Antilles',
        'AO':'Angola',
        'AQ':'Antarctica',
        'AR':'Argentina',
        'AS':'American Samoa',
        'AT':'Austria',
        'AU':'Australia',
        'AW':'Aruba',
        'AZ':'Azerbaijan',
        'BA':'Bosnia and Herzegovina',
        'BB':'Barbados',
        'BD':'Bangladesh',
        'BE':'Belgium',
        'BF':'Burkina Faso',
        'BG':'Bulgaria',
        'BH':'Bahrain',
        'BI':'Burundi',
        'BJ':'Benin',
        'BL':'Saint Barthelemy',
        'BM':'Bermuda',
        'BN':'Brunei',
        'BO':'Bolivia',
        'BR':'Brazil',
        'BS':'Bahamas',
        'BT':'Bhutan',
        'BW':'Botswana',
        'BY':'Belarus',
        'BZ':'Belize',
        'CA':'Canada',
        'CC':'Cocos (Keeling) Islands',
        'CD':'Democratic Republic of the Congo',
        'CF':'Central African Republic',
        'CG':'Republic of the Congo',
        'CH':'Switzerland',
        'CI':'Ivory Coast',
        'CK':'Cook Islands',
        'CL':'Chile',
        'CM':'Cameroon',
        'CN':'China',
        'CO':'Colombia',
        'CR':'Costa Rica',
        'CU':'Cuba',
        'CV':'Cape Verde',
        'CX':'Christmas Island',
        'CY':'Cyprus',
        'CZ':'Czech Republic',
        'DE':'Germany',
        'DJ':'Djibouti',
        'DK':'Denmark',
        'DM':'Dominica',
        'DO':'Dominican Republic',
        'DZ':'Algeria',
        'EC':'Ecuador',
        'EE':'Estonia',
        'EG':'Egypt',
        'EH':'Western Sahara',
        'ER':'Eritrea',
        'ES':'Spain',
        'ET':'Ethiopia',
        'FI':'Finland',
        'FJ':'Fiji',
        'FK':'Falkland Islands',
        'FM':'Micronesia',
        'FO':'Faroe Islands',
        'FR':'France',
        'GA':'Gabon',
        'GB':'United Kingdom',
        'GD':'Grenada',
        'GE':'Georgia',
        'GH':'Ghana',
        'GI':'Gibraltar',
        'GL':'Greenland',
        'GM':'Gambia',
        'GN':'Guinea',
        'GQ':'Equatorial Guinea',
        'GR':'Greece',
        'GT':'Guatemala',
        'GU':'Guam',
        'GW':'Guinea-Bissau',
        'GY':'Guyana',
        'HK':'Hong Kong',
        'HN':'Honduras',
        'HR':'Croatia',
        'HT':'Haiti',
        'HU':'Hungary',
        'ID':'Indonesia',
        'IE':'Ireland',
        'IL':'Israel',
        'IM':'Isle of Man',
        'IN':'India',
        'IO':'British Indian Ocean Territory',
        'IQ':'Iraq',
        'IR':'Iran',
        'IS':'Iceland',
        'IT':'Italy',
        'JE':'Jersey',
        'JM':'Jamaica',
        'JO':'Jordan',
        'JP':'Japan',
        'KE':'Kenya',
        'KG':'Kyrgyzstan',
        'KH':'Cambodia',
        'KI':'Kiribati',
        'KM':'Comoros',
        'KN':'Saint Kitts and Nevis',
        'KP':'North Korea',
        'KR':'South Korea',
        'KW':'Kuwait',
        'KY':'Cayman Islands',
        'KZ':'Kazakhstan',
        'LA':'Laos',
        'LB':'Lebanon',
        'LC':'Saint Lucia',
        'LI':'Liechtenstein',
        'LK':'Sri Lanka',
        'LR':'Liberia',
        'LS':'Lesotho',
        'LT':'Lithuania',
        'LU':'Luxembourg',
        'LV':'Latvia',
        'LY':'Libya',
        'MA':'Morocco',
        'MC':'Monaco',
        'MD':'Moldova',
        'ME':'Montenegro',
        'MF':'Saint Martin',
        'MG':'Madagascar',
        'MH':'Marshall Islands',
        'MK':'Macedonia',
        'ML':'Mali',
        'MM':'Burma (Myanmar)',
        'MN':'Mongolia',
        'MO':'Macau',
        'MP':'Northern Mariana Islands',
        'MR':'Mauritania',
        'MS':'Montserrat',
        'MT':'Malta',
        'MU':'Mauritius',
        'MV':'Maldives',
        'MW':'Malawi',
        'MX':'Mexico',
        'MY':'Malaysia',
        'MZ':'Mozambique',
        'NA':'Namibia',
        'NC':'New Caledonia',
        'NE':'Niger',
        'NFK':'Norfolk Island',
        'NG':'Nigeria',
        'NI':'Nicaragua',
        'NL':'Netherlands',
        'NO':'Norway',
        'NP':'Nepal',
        'NR':'Nauru',
        'NU':'Niue',
        'NZ':'New Zealand',
        'OM':'Oman',
        'PA':'Panama',
        'PE':'Peru',
        'PF':'French Polynesia',
        'PG':'Papua New Guinea',
        'PH':'Philippines',
        'PK':'Pakistan',
        'PL':'Poland',
        'PM':'Saint Pierre and Miquelon',
        'PN':'Pitcairn Islands',
        'PR':'Puerto Rico',
        'PT':'Portugal',
        'PW':'Palau',
        'PY':'Paraguay',
        'QA':'Qatar',
        'RO':'Romania',
        'RS':'Serbia',
        'RU':'Russia',
        'RW':'Rwanda',
        'SA':'Saudi Arabia',
        'SB':'Solomon Islands',
        'SC':'Seychelles',
        'SD':'Sudan',
        'SE':'Sweden',
        'SG':'Singapore',
        'SH':'Saint Helena',
        'SI':'Slovenia',
        'SJ':'Svalbard',
        'SK':'Slovakia',
        'SL':'Sierra Leone',
        'SM':'San Marino',
        'SN':'Senegal',
        'SO':'Somalia',
        'SR':'Suriname',
        'ST':'Sao Tome and Principe',
        'SV':'El Salvador',
        'SY':'Syria',
        'SZ':'Swaziland',
        'TC':'Turks and Caicos Islands',
        'TD':'Chad',
        'TG':'Togo',
        'TH':'Thailand',
        'TJ':'Tajikistan',
        'TK':'Tokelau',
        'TL':'Timor-Leste',
        'TM':'Turkmenistan',
        'TN':'Tunisia',
        'TO':'Tonga',
        'TR':'Turkey',
        'TT':'Trinidad and Tobago',
        'TV':'Tuvalu',
        'TW':'Taiwan',
        'TZ':'Tanzania',
        'UA':'Ukraine',
        'UG':'Uganda',
        'US':'United States',
        'UY':'Uruguay',
        'UZ':'Uzbekistan',
        'VA':'Holy See (Vatican City)',
        'VC':'Saint Vincent and the Grenadines',
        'VE':'Venezuela',
        'VG':'British Virgin Islands',
        'VI':'US Virgin Islands',
        'VN':'Vietnam',
        'VU':'Vanuatu',
        'WF':'Wallis and Futuna',
        'WS':'Samoa',
        'YE':'Yemen',
        'YT':'Mayotte',
        'ZA':'South Africa',
        'ZM':'Zambia',
        'ZW':'Zimbabwe',
        'EU':'European Union'
            }
